#!/usr/bin/python3

# Command Line Runner for Stock Analyser

import json
import traceback

import lib.utils.version_check
from lib.utils.session import Session
from lib.utils.args import args
from lib.utils.args import debug
from lib.fetcher import fetch
from lib.scraper import scrape
from lib.analyser import calc_params

debug("Using LIMIT {}".format(args.limit))

try:
    session = Session().getSession()
    tickers = fetch(session, args.limit)
    stocks = [scrape(session, ticker) for ticker in tickers]

    for stock in stocks:
        calc_params(stock)


    if args.print_output:
        for stock in stocks:
            debug("\nP&L:")
            debug(stock.financial_data_raw.to_string())
            debug("\nCashflow:")
            debug(stock.cashflow_data_raw.to_string())
            debug("\nBalance Sheet:")
            debug(stock.balance_sheet_data_raw.to_string())
            debug("\nAnnual Reports:")
            debug(json.dumps(stock.annual_reports))
            debug("\nCredit Ratings:")
            debug(json.dumps(stock.credit_ratings))
            debug("\nFinancial Ratios:")
            debug(stock.financial_ratios.to_string())

except Exception as err:
    debug("Programme failed.", force=True)
    debug(err)
    traceback.print_exc()